### PR TITLE
25 minimum viable produce create template for challenge submission

### PR DESCRIPTION
**Pull request by RedBlueCarrots**
Extended the view page to add challenge submission

Functionally here, some room for re-work / redesign later on.

Form routing is all functional as is done with dynamic DOM changing in js.

A separate layout exists for desktop and mobile.

image

image

### CODE REVIEW

**Comment by DeltaO3** [comment]
Code looks good - Minor nitpick that i have already brought up, i think conventionally minus should be on the left side of plus - and "My Path" should be further left on desktop? empty space doing nothing but detracting from the look. 
The whole alignment of desktop is off (submit is off centre and thats bad), but i suppose this could be fixed later.
Could we put submit below the 2 buttons on mobile also?

**Comment by RedBlueCarrots** [comment]
Atm submit the attempt on desktop is centred to the input field not the whole page - imo it looks better but that might just be me

And good catch, I intended to make the title on desktop left aligned but it didn't work apparently.

Mobile buttons I can make plus and minus on separate rows to submit.
Idk why I feel this plus minus arrangement works better, I'd be curious to see others opinion on it

**Comment by DeltaO3** [comment]
the colours of submit and plus next to each other is bad and clashes.

Also, the submit button that opens the field feels like it creates a bunch of un-necessary empty space? I personally am of the opinion that we dont even need to hide submission to a user as if they click on an issue they are likely wanting to submit anyway

**Comment by RedBlueCarrots** [comment]
image
image

**Comment by RedBlueCarrots** [comment]
Hovering over inputs to add/remove rows is a good idea, but i think is beyond MVP

**Comment by DeltaO3** [comment]
I definitely think mobile looks much better, I think desktop is fine for now. I think we need more discussion about what to do but i think for MVP this is good, and we can do more style thoughts later once everything works. I'll approve this, but maybe wait for any more opinions.

**Review by DeltaO3 — APPROVED** [review]

**Review by RadiationOcelot — APPROVED** [review]
LGTM

**Pull request merged**
